[
  {
    "failure": {
      "humanReason": "Uncaught Exception: TypeError('BAD DOGE',)"
    },
    "name": "$result"
  }
]