[
  {
    "failure": {
      "humanReason": "Uncaught Exception: TypeError(\"While assigning key 'test_me': Expected 'this should fail' to be of type <type 'int'>\",)"
    },
    "name": "$result"
  }
]